# Generated by Django 3.0.6 on 2020-06-19 15:27

import app.models
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# app.migrations.0007_auto_20200607_1319


def create_through_relations(apps, schema_editor):
    Guild = apps.get_model('app', 'Guild')
    GuildMembership = apps.get_model('app', 'GuildMembership')
    for guild in Guild.objects.all():
        for member in guild.members.all():
            GuildMembership.objects.create(tuser=member, guild=guild)


class Migration(migrations.Migration):

    replaces = [('app', '0002_auto_20200531_1551'), ('app', '0003_auto_20200531_1734'), ('app', '0004_auto_20200531_1829'), ('app', '0005_guild_additional_notifications'), ('app', '0006_auto_20200607_1318'), ('app', '0007_auto_20200607_1319'), ('app', '0008_remove_guild_members'), ('app', '0009_guild_members'), ('app', '0010_temporarynpc'), ('app', '0011_temporarynpc_expired')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0001_squashed_0004_auto_20200523_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('time', models.DateTimeField()),
                ('job_id', models.CharField(max_length=36)),
                ('canceled', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now=True)),
            ],
            bases=(app.models.ActionMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='InfluenceCollection',
        ),
        migrations.AddField(
            model_name='resourcecollection',
            name='by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.TelegramUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcecollection',
            name='in_guild',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.Guild'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcecollection',
            name='at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='guild',
            name='additional_notifications',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=16)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Guild')),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TelegramUser')),
            ],
        ),
        migrations.RunPython(
            # code=app.migrations.0007_auto_20200607_1319.create_through_relations,
            create_through_relations,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='guild',
            name='members',
        ),
        migrations.AddField(
            model_name='guild',
            name='members',
            field=models.ManyToManyField(related_name='guilds', through='app.GuildMembership', to='app.TelegramUser'),
        ),
        migrations.CreateModel(
            name='TemporaryNPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField()),
                ('caption', models.CharField(max_length=50)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.TelegramUser')),
                ('in_guild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Guild')),
                ('expired', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
