# Generated by Django 3.0.6 on 2020-05-31 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200531_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecollection',
            name='at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resourcecollection',
            name='by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.TelegramUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcecollection',
            name='in_guild',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.Guild'),
            preserve_default=False,
        ),
    ]
