# Generated by Django 3.0.6 on 2020-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200531_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resourcecollection',
            name='at',
            field=models.DateTimeField(),
        ),
    ]
