# Generated by Django 3.0.6 on 2020-06-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_guild_additional_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='job_id',
            field=models.CharField(max_length=36),
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=16)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Guild')),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TelegramUser')),
            ],
        ),
    ]
