# Generated by Django 3.0.6 on 2020-06-07 10:19

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Guild = apps.get_model('app', 'Guild')
    GuildMembership = apps.get_model('app', 'GuildMembership')
    for guild in Guild.objects.all():
        for member in guild.members.all():
            GuildMembership.objects.create(tuser=member, guild=guild)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200607_1318'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop)
    ]
