# Generated by Django 3.0.6 on 2020-06-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200607_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='members',
        ),
    ]
