# Generated by Django 3.0.6 on 2020-06-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_guild_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='members',
            field=models.ManyToManyField(related_name='guilds', through='app.GuildMembership', to='app.TelegramUser'),
        ),
    ]
