# Generated by Django 3.0.6 on 2020-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_temporarynpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarynpc',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
